FROM node:16

WORKDIR /var/www

COPY . .

EXPOSE 8080

ARG PRISMIC_SECRET
ARG HEROKU
ARG GOOGLE_PRIVATE_KEY
ARG GOOGLE_CLIENT_EMAIL
ARG CREATESEND_LIST
ARG CREATESEND_KEY
ARG CLOUDINARY_SECRET
ARG CLOUDINARY_KEY
ARG CLOUDFLARE_ZONE
ARG CLOUDFLARE_KEY
ARG CLOUDFLARE_EMAIL
ARG ANALYTICS_VIEW_ID

ENV NODE_ENV "production"
ENV PRISMIC_SECRET $PRISMIC_SECRET
ENV HEROKU $HEROKU
ENV GOOGLE_PRIVATE_KEY $GOOGLE_PRIVATE_KEY
ENV GOOGLE_CLIENT_EMAIL $GOOGLE_CLIENT_EMAIL
ENV CREATESEND_LIST $CREATESEND_LIST
ENV CREATESEND_KEY $CREATESEND_KEY
ENV CLOUDINARY_SECRET $CLOUDINARY_SECRET
ENV CLOUDINARY_KEY $CLOUDINARY_KEY
ENV CLOUDFLARE_ZONE $CLOUDFLARE_ZONE
ENV CLOUDFLARE_KEY $CLOUDFLARE_KEY
ENV CLOUDFLARE_EMAIL $CLOUDFLARE_EMAIL
ENV ANALYTICS_VIEW_ID $ANALYTICS_VIEW_ID

RUN npm install
RUN npm run build

CMD ["npm", "run", "start"]